serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'kubernetes-pods-metrics'
        kubernetes_sd_configs:
          - role: pod
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'container_cpu_usage_seconds_total|container_memory_working_set_bytes|container_network_receive_bytes_total|container_network_transmit_bytes_total'
            action: keep
